[package]
name = "r_tank_battle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
piston_window = "0.127.0"
gfx = "0.18.3"
gfx_device_gl = "0.16.2"
piston2d-gfx_graphics = "0.79.0"
